backend:
  name: github
  repo: Skeith918/consultation-hubvisory # Path to your Github repository
  branch: master # Branch to update
media_folder: "img"
publish_mode: editorial_workflow
collections:
  outil:
    output: true
  usage:
    output: true
